<?xml version="1.0" encoding="UTF-8"?><testrun name="TestSkipList" project="P1" tests="7" started="7" failures="0" errors="1" ignored="0">
  <testsuite name="TestSkipList" time="10.014">
    <testcase name="testInsert" classname="TestSkipList" time="0.004"/>
    <testcase name="testSearch" classname="TestSkipList" time="0.002"/>
    <testcase name="testRemoveByKey" classname="TestSkipList" time="0.001"/>
    <testcase name="testRemoveByCoordinates" classname="TestSkipList" time="0.001"/>
    <testcase name="testSize" classname="TestSkipList" time="0.001"/>
    <testcase name="testDump" classname="TestSkipList" time="0.001"/>
    <testcase name="testIntersection" classname="TestSkipList" time="10.004">
      <error>org.junit.runners.model.TestTimedOutException: test timed out after 10 seconds
	at java.base@11.0.16/java.lang.StringLatin1.newString(StringLatin1.java:715)
	at java.base@11.0.16/java.lang.StringBuilder.toString(StringBuilder.java:452)
	at app//SkipList.intersection(SkipList.java:230)
	at app//TestSkipList.testIntersection(TestSkipList.java:92)
	at java.base@11.0.16/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.16/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.16/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.16/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at app//org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at app//org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at app//student.testingsupport.junit4.RunTestMethodWrapper.evaluate(RunTestMethodWrapper.java:74)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at app//org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base@11.0.16/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base@11.0.16/java.lang.Thread.run(Thread.java:829)

</error>
    </testcase>
  </testsuite>
</testrun>
